# Generated by Django 2.2 on 2019-06-16 08:42

import chatgroup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='checkin_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'annonyment join'), (1, 'use invite_code'), (2, 'use question and answer')], default=1, verbose_name='checkin_method'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_info',
            field=models.TextField(blank=True, default=chatgroup.models.get_default_info, null=True, verbose_name='group_info'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=30, verbose_name='group_name'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='group id'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='invite_code',
            field=models.CharField(default=chatgroup.models.get_default_invite_code, max_length=30, verbose_name='invite_code'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='join_deltatime',
            field=models.DurationField(default=chatgroup.models.get_default_timedelta, verbose_name='join_deltatime'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatgroups', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
    ]
