# Generated by Django 2.2 on 2019-06-16 11:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatgroup', '0002_auto_20190616_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_image',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='group uuid'),
        ),
    ]
